/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;


import Entity.Coaches;

import sportingclub.Tools;


/**
 *
 * @author VicTuS
 */
public class Coachfrm extends javax.swing.JFrame {

    /**
     * Creates new form Coach
     */
    public Coachfrm() {
        initComponents();
        // Stretch Image
       /* Icon i = searchButton.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(searchButton.getWidth(),searchButton.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon.setIcon(new ImageIcon(image));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Clearbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Allbtn = new javax.swing.JButton();
        Findbtn1 = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        Addbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        IDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        DeptField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons/icons8-back-25.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons/search.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 20));
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 130, 30));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 218, 10, 360));

        jTable1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Departement", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 217, 630, 360));

        Clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        Clearbtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Clearbtn.setForeground(new java.awt.Color(255, 102, 102));
        Clearbtn.setText("Clear");
        Clearbtn.setBorder(null);
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Coaches");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, 70));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 20));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Departement:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, 20));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Filtered by:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 110, 30));

        Allbtn.setBackground(new java.awt.Color(204, 204, 204));
        Allbtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Allbtn.setForeground(new java.awt.Color(255, 102, 102));
        Allbtn.setText("All");
        Allbtn.setBorder(null);
        Allbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Allbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 60, 30));

        Findbtn1.setBackground(new java.awt.Color(204, 204, 204));
        Findbtn1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Findbtn1.setForeground(new java.awt.Color(255, 102, 102));
        Findbtn1.setText("Find");
        Findbtn1.setBorder(null);
        Findbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Findbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Findbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 50, 30));

        Updatebtn.setBackground(new java.awt.Color(204, 204, 204));
        Updatebtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(255, 102, 102));
        Updatebtn.setText("Update");
        Updatebtn.setBorder(null);
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 60, 30));

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 153, 153));
        jButton20.setText("Log out");
        jButton20.setBorder(null);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 70, -1));

        Addbtn.setBackground(new java.awt.Color(204, 204, 204));
        Addbtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(255, 102, 102));
        Addbtn.setText("Add");
        Addbtn.setBorder(null);
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 60, 30));

        Deletebtn.setBackground(new java.awt.Color(204, 204, 204));
        Deletebtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Deletebtn.setForeground(new java.awt.Color(255, 102, 102));
        Deletebtn.setText("Delete");
        Deletebtn.setBorder(null);
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 60, 30));

        IDField.setEditable(false);
        IDField.setBackground(new java.awt.Color(255, 255, 255));
        IDField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        IDField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 210, -1));

        NameField.setBackground(new java.awt.Color(255, 255, 255));
        NameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        NameField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 210, -1));

        DeptField.setBackground(new java.awt.Color(255, 255, 255));
        DeptField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        DeptField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(DeptField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 210, -1));

        EmailField.setBackground(new java.awt.Color(255, 255, 255));
        EmailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        EmailField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 210, -1));

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 500, 630));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1080, 600));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Coaches ch = new Coaches();
    private void clearData()
    {
        Tools.clearText(this);
        IDField.setText(ch.getAutoNumber());
        Addbtn.setEnabled(true);
        Updatebtn.setEnabled(false);
        Deletebtn.setEnabled(false);
        NameField.requestFocus();
        
        
    }
    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed

       clearData();
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void AllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllbtnActionPerformed
        
        ch.getAllRows(jTable1);
// TODO add your handling code here:
    }//GEN-LAST:event_AllbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        setValues();
        ch.update();
        clearData();  
        ch.getAllRows(jTable1);
// TODO add your handling code here:
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed
    private void setValues()
    {
        
            ch.setCoachId(Integer.parseInt(IDField.getText()));
            ch.setCoachName(NameField.getText());
            ch.setCoachEmail(EmailField.getText());
            ch.setCoachSpecialty(DeptField.getText());
           
            
    }
    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        setValues();
        ch.add();
        clearData();
        ch.getAllRows(jTable1);

    }//GEN-LAST:event_AddbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
       if(Tools.confirmMsg("Are you sure You want to delete ?!"))
       {
        setValues();
        ch.delete();
        clearData();
        ch.getAllRows(jTable1);
       }
        

// TODO add your handling code here:
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    clearData();
    ch.getAllRows(jTable1);
     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void Findbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Findbtn1ActionPerformed
            String strCoachNO = (String)Tools.InputBox("Enter Coach ID ");
            int CoachNO = Integer.parseInt(strCoachNO);
            ch.setCoachId(CoachNO);
            ch.getOneRow(jTable1);// TODO add your handling code here:
    }//GEN-LAST:event_Findbtn1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int row = jTable1.getSelectedRow();
            String strNO = jTable1.getValueAt(row,0).toString();
            String strName = jTable1.getValueAt(row,1).toString();
            String strDept = jTable1.getValueAt(row,2).toString();
            String strEmail = jTable1.getValueAt(row,3).toString();
            
            IDField.setText(strNO);
            NameField.setText(strName);
            DeptField.setText(strDept);
            EmailField.setText(strEmail);
            
            Addbtn.setEnabled(false);
            Updatebtn.setEnabled(true);
            Deletebtn.setEnabled(true);
            
        }
        catch(Exception ex){
            Tools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
MainPagefrm m1 = new MainPagefrm();
m1.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jLabel10MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coachfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coachfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coachfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coachfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coachfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Allbtn;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JTextField DeptField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton Findbtn1;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
