/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import Entity.Managers;

import sportingclub.Tools;

/**
 *
 * @author VicTuS
 */
public class Managerfrm extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Managerfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        SearchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        DeptField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Allbtn = new javax.swing.JButton();
        Addbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Findbtn = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Jlabell = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Manager");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, 40));

        jButton9.setBackground(new java.awt.Color(255, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton9.setText("Log out");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 70, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Departement", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 217, 630, 360));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 218, 10, 360));
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 130, -1));
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 180, 20, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Filtered by:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 80, 20));

        IDField.setEditable(false);
        IDField.setBackground(new java.awt.Color(255, 255, 255));
        IDField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        IDField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 210, -1));

        NameField.setBackground(new java.awt.Color(255, 255, 255));
        NameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        NameField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 210, -1));

        DeptField.setBackground(new java.awt.Color(255, 255, 255));
        DeptField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        DeptField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(DeptField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 210, -1));

        EmailField.setBackground(new java.awt.Color(255, 255, 255));
        EmailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        EmailField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 210, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 80, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Departement:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 100, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, 20));

        Allbtn.setBackground(new java.awt.Color(255, 102, 102));
        Allbtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Allbtn.setText("ALL");
        Allbtn.setBorder(null);
        Allbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Allbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 70, -1));

        Addbtn.setBackground(new java.awt.Color(255, 102, 102));
        Addbtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.setBorder(null);
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 70, -1));

        Updatebtn.setBackground(new java.awt.Color(255, 102, 102));
        Updatebtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Updatebtn.setText("Update");
        Updatebtn.setBorder(null);
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 70, -1));

        Deletebtn.setBackground(new java.awt.Color(255, 102, 102));
        Deletebtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.setBorder(null);
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 70, -1));

        Findbtn.setBackground(new java.awt.Color(255, 102, 102));
        Findbtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Findbtn.setText("Find");
        Findbtn.setBorder(null);
        Findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Findbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 70, -1));

        Clearbtn.setBackground(new java.awt.Color(255, 102, 102));
        Clearbtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Clearbtn.setText("Clear");
        Clearbtn.setBorder(null);
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 70, 20));

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 500, 630));

        Jlabell.setBackground(new java.awt.Color(255, 102, 102));
        Jlabell.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(Jlabell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Managers mng = new Managers();
    private void clearData()
    {
        Tools.clearText(this);
        IDField.setText(mng.getAutoNumber());
        Addbtn.setEnabled(true);
        Updatebtn.setEnabled(false);
        Deletebtn.setEnabled(false);
        NameField.requestFocus();
        
        
    }
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        Login r1 = new Login();
        r1.setVisible(true);     // Link sign up --> Registration Page
        this.setVisible(false);

    }//GEN-LAST:event_jButton9ActionPerformed
    private void setValues()
    {
        
            mng.setMangerId(Integer.parseInt(IDField.getText()));
            mng.setName(NameField.getText());
            mng.setDepartment(DeptField.getText());
             mng.setEmail(EmailField.getText());
            
           
            
    }
    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        setValues();
        mng.add();
        clearData();
        mng.getAllRows(jTable1);// TODO add your handling code here:
    }//GEN-LAST:event_AddbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        setValues();
        mng.update();
        clearData();  
        mng.getAllRows(jTable1);// TODO add your handling code here:
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        if(Tools.confirmMsg("Are you sure You want to delete ?!"))
       {
        setValues();
        mng.delete();
        clearData();
        mng.getAllRows(jTable1);
       }// TODO add your handling code here:
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void FindbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindbtnActionPerformed
       String strCoachNO = (String)Tools.InputBox("Enter Manager ID ");
            int CoachNO = Integer.parseInt(strCoachNO);
            mng.setMangerId(CoachNO);
            mng.getOneRow(jTable1); // TODO add your handling code here:
    }//GEN-LAST:event_FindbtnActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed

        clearData(); 
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int row = jTable1.getSelectedRow();
            String strNO = jTable1.getValueAt(row,0).toString();
            String strName = jTable1.getValueAt(row,1).toString();
            String strDept = jTable1.getValueAt(row,2).toString();
            String strEmail = jTable1.getValueAt(row,3).toString();
            
            IDField.setText(strNO);
            NameField.setText(strName);
            DeptField.setText(strDept);
            EmailField.setText(strEmail);
            
            Addbtn.setEnabled(false);
            Updatebtn.setEnabled(true);
            Deletebtn.setEnabled(true);
            
        }
        catch(Exception ex){
            Tools.msgBox(ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        clearData();
    mng.getAllRows(jTable1);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void AllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllbtnActionPerformed
    mng.getAllRows(jTable1);    // TODO add your handling code here:
    }//GEN-LAST:event_AllbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Managerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Managerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Managerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Managerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managerfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Allbtn;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JTextField DeptField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton Findbtn;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel Jlabell;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
