/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Entity.Member;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sportingclub.Tools;

/**
 *
 * @author VicTuS
 */
public class Memberfrm extends javax.swing.JFrame {

    /**
     * Creates new form Member
     */
    public Memberfrm() {
        initComponents();
            // Stretch Image
      //  Icon i = ImageIcon.getIcon();
        //ImageIcon icon = (ImageIcon)i;
        //Image image = icon.getImage().getScaledInstance(ImageIcon.getWidth(),ImageIcon.getHeight(), Image.SCALE_SMOOTH);
        //ImageIcon.setIcon(new ImageIcon(image));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DateField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        SubField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        Allbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Findbtn = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();
        EmailField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 218, 10, 360));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/search.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, 50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Email", "Date", "Name", "Subscription ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 217, 630, 360));

        DateField.setBackground(new java.awt.Color(255, 255, 255));
        DateField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        DateField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Members");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 220, 60));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Filtered by:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 130, 30));
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 130, 30));

        IDField.setBackground(new java.awt.Color(255, 255, 255));
        IDField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        IDField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 210, -1));

        SubField.setBackground(new java.awt.Color(255, 255, 255));
        SubField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        SubField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(SubField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 210, -1));

        NameField.setBackground(new java.awt.Color(255, 255, 255));
        NameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        NameField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Subscription ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 20));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Join Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 100, 20));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, 20));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("Email:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 80, 20));

        Addbtn.setBackground(new java.awt.Color(255, 102, 102));
        Addbtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(255, 255, 255));
        Addbtn.setText("Add");
        Addbtn.setBorder(null);
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 80, 40));

        Allbtn.setBackground(new java.awt.Color(255, 102, 102));
        Allbtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Allbtn.setForeground(new java.awt.Color(255, 255, 255));
        Allbtn.setText("All");
        Allbtn.setBorder(null);
        Allbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Allbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 80, 40));

        Updatebtn.setBackground(new java.awt.Color(255, 102, 102));
        Updatebtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        Updatebtn.setText("Update");
        Updatebtn.setBorder(null);
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 80, 40));

        Deletebtn.setBackground(new java.awt.Color(255, 102, 102));
        Deletebtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        Deletebtn.setText("Delete");
        Deletebtn.setBorder(null);
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 80, 40));

        Findbtn.setBackground(new java.awt.Color(255, 102, 102));
        Findbtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Findbtn.setForeground(new java.awt.Color(255, 255, 255));
        Findbtn.setText("Find");
        Findbtn.setBorder(null);
        Findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Findbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 80, 40));

        Clearbtn.setBackground(new java.awt.Color(255, 102, 102));
        Clearbtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        Clearbtn.setText("Clear");
        Clearbtn.setBorder(null);
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 80, 40));

        EmailField.setBackground(new java.awt.Color(255, 255, 255));
        EmailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 102)));
        EmailField.setSelectionColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 210, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-back-25.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 40));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1070, 610));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 500, 630));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Member ch = new Member();
    private void clearData()
    {
        Tools.clearText(this);
        IDField.setText(ch.getAutoNumber());
        Addbtn.setEnabled(true);
        Updatebtn.setEnabled(false);
        Deletebtn.setEnabled(false);
        NameField.requestFocus();
        
        
    }
    
     private void setValues()
    {
        
            ch.setMemberId(Integer.parseInt(IDField.getText()));
            ch.setFirstName(NameField.getText());
            ch.setJoinDate(DateField.getText());
            ch.setEmail(EmailField.getText());
            ch.setSubscriptionId(Integer.parseInt(SubField.getText()));
           
            
    }
     
    private void AllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllbtnActionPerformed
        ch.getAllRows(jTable1);// TODO add your handling code here:
    }//GEN-LAST:event_AllbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
       setValues();
        ch.update();
        clearData();  
        ch.getAllRows(jTable1); // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        if(Tools.confirmMsg("Are you sure You want to delete ?!"))
       {
        setValues();
        ch.delete();
        clearData();
        ch.getAllRows(jTable1);
       }// TODO add your handling code here:
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void FindbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindbtnActionPerformed
       String strCoachNO = (String)Tools.InputBox("Enter Coach ID ");
            int CoachNO = Integer.parseInt(strCoachNO);
            ch.setMemberId(CoachNO);
            ch.getOneRow(jTable1); // TODO add your handling code here:
    }//GEN-LAST:event_FindbtnActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed

             clearData();

    }//GEN-LAST:event_ClearbtnActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
       setValues();
        ch.add();
        clearData();
        ch.getAllRows(jTable1); // TODO add your handling code here:
    }//GEN-LAST:event_AddbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        clearData();
        ch.getAllRows(jTable1);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int row = jTable1.getSelectedRow();
            String strNO = jTable1.getValueAt(row,0).toString();
            String strName = jTable1.getValueAt(row,1).toString();
            String strDate = jTable1.getValueAt(row,2).toString();
            String strEmail = jTable1.getValueAt(row,3).toString();
            String strSub = jTable1.getValueAt(row,4).toString();
            
            IDField.setText(strNO);
            NameField.setText(strEmail);
            DateField.setText(strDate);
            EmailField.setText(strName);
            SubField.setText(strSub);
            
            Addbtn.setEnabled(false);
            Updatebtn.setEnabled(true);
            Deletebtn.setEnabled(true);
            
        }
        catch(Exception ex){
            Tools.msgBox(ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        MainPagefrm m1 = new MainPagefrm();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memberfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memberfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memberfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memberfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memberfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Allbtn;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JTextField DateField;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton Findbtn;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTextField SubField;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
