/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sportingclub.Tools;
import Entity.TrainingSessions;
import java.util.Date;
import java.text.DateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author VicTuS
 */
public class TrainingSessionfrm extends javax.swing.JFrame {

    /**
     * Creates new form TrainingSession
     */
    public TrainingSessionfrm() {
        initComponents();
        // Stretch Image
       // Icon i = ImageIcon.getIcon();
        //ImageIcon icon = (ImageIcon)i;
        //Image image = icon.getImage().getScaledInstance(ImageIcon.getWidth(),ImageIcon.getHeight(), Image.SCALE_SMOOTH);
        //ImageIcon.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton16 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        Clearbtn = new controls.JMyButton();
        Deletebtn = new controls.JMyButton();
        Updatebtn = new controls.JMyButton();
        Addbtn = new controls.JMyButton();
        DateField = new javax.swing.JTextField();
        DurationField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        TeamField = new javax.swing.JTextField();
        CoachField = new javax.swing.JTextField();
        NotesField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jButton16.setBackground(new java.awt.Color(255, 102, 102));
        jButton16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton16.setText("Coash");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Duration", "Notes", "TeamID", "CoachID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 217, 630, 360));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Filtered by:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 80, 20));
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 130, -1));
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 180, 20, 20));

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Training Sessions");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 210, 40));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 218, 10, 360));

        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        DateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 160, -1));

        DurationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurationFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DurationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, -1));
        getContentPane().add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 160, -1));
        getContentPane().add(TeamField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 160, -1));

        CoachField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CoachField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 160, -1));

        NotesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NotesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 160, -1));

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 60, 20));

        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Duration");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("TeamID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 60, 20));

        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("CoachID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 60, 30));

        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Notes");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1080, 600));

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 500, 630));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed
    TrainingSessions trn = new TrainingSessions();
    private void clearData()
    {
        Tools.clearText(this);
        IDField.setText(trn.getAutoNumber());
        Addbtn.setEnabled(true);
        Updatebtn.setEnabled(false);
        Deletebtn.setEnabled(false);
        DateField.requestFocus();
        
        
    }
    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        clearData();
        trn.getAllRows(jTable1);
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void DateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        trn.getAllRows(jTable1);

        clearData();    }//GEN-LAST:event_formWindowOpened
    private void setValues()
    {
        
            trn.setSessionId(Integer.parseInt(IDField.getText()));
            //DateTimeFormatter s1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            //LocalDate d1= LocalDate.parse(DateField.getText(),s1);
            trn.setDate(DateField.getText());
            trn.setDuration(Float.parseFloat(DurationField.getText()));
            trn.setNotes(TeamField.getText());
            trn.setCoachId(Integer.parseInt(CoachField.getText()));
            trn.setTeamId(Integer.parseInt(TeamField.getText()));
        
    }
    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        setValues();
        trn.add();
        clearData();
        trn.getAllRows(jTable1);
// TODO add your handling code here:
    }//GEN-LAST:event_AddbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        setValues();
        trn.update();
        clearData();
        trn.getAllRows(jTable1);
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        setValues();
        trn.delete();
        clearData();
        trn.getAllRows(jTable1);
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void DurationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DurationFieldActionPerformed

    private void CoachFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoachFieldActionPerformed

    private void NotesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotesFieldActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
try{
            int row = jTable1.getSelectedRow();
            String strNO = jTable1.getValueAt(row,0).toString();
            String strName = jTable1.getValueAt(row,1).toString();
            String strDept = jTable1.getValueAt(row,2).toString();
            String strEmail = jTable1.getValueAt(row,3).toString();
            String strDur = jTable1.getValueAt(row,4).toString();
            String strDate = jTable1.getValueAt(row,5).toString();
            
            IDField.setText(strNO);
            CoachField.setText(strName);
            TeamField.setText(strDept);
            NotesField.setText(strEmail);
            DurationField.setText(strDur);
            DateField.setText(strDate);
            
            Addbtn.setEnabled(false);
            Updatebtn.setEnabled(true);
            Deletebtn.setEnabled(true);
            
        }
        catch(Exception ex){
            Tools.msgBox(ex.getMessage());
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingSessionfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingSessionfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingSessionfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingSessionfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainingSessionfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton Addbtn;
    private controls.JMyButton Clearbtn;
    private javax.swing.JTextField CoachField;
    private javax.swing.JTextField DateField;
    private controls.JMyButton Deletebtn;
    private javax.swing.JTextField DurationField;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField NotesField;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTextField TeamField;
    private controls.JMyButton Updatebtn;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
